# Site settings
title: Dmitry Stepanov
name: Dmitry Stepanov
email: ateds@list.ru
description: >
  Thoughts about life, technology, development, and blog by Dmitry Stepanov.
baseurl: ""
url: "https://dmitrystepanov.net"
enforce_ssl: "dmitrystepanov.net"

future: true
paginate: 100

markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Where things are
source              : .

layouts_dir         : _layouts
includes_dir        : _includes

